Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'up_protocol')
src	= Split("""



""")

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('up_protocol', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
